// This file is auto-generated by scripts/generate-static-policies-data.ts — do not edit manually.
// Source: Redis 8.8.0, 415 commands.
import { ModulePolicyRecords } from "./types";

export const POLICIES: ModulePolicyRecords = {
  "ft": {
    "aggregate": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "aliasadd": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "aliasdel": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "aliasupdate": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "alter": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "create": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "cursor": {
      "request": "special",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "read": {
          "request": "special",
          "response": "default-keyless",
          "isKeyless": true
        },
        "del": {
          "request": "special",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "dictadd": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "dictdel": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "dictdump": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "drop": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "dropindex": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "explain": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "explaincli": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "info": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "profile": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "search": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "spellcheck": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "sugadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sugdel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sugget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "suglen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "syndump": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "synupdate": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "tagvals": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    }
  },
  "bf": {
    "add": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "card": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "debug": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "exists": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "insert": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "loadchunk": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "madd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "mexists": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "reserve": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "scandump": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "cf": {
    "add": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "addnx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "compact": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "count": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "debug": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "del": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "exists": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "insert": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "insertnx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "loadchunk": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "mexists": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "reserve": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "scandump": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "cms": {
    "incrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "initbydim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "initbyprob": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "merge": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "query": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "json": {
    "arrappend": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arrindex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arrinsert": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arrlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arrpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arrtrim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "clear": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "debug": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "del": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "forget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "get": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "merge": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "mget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "mset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "numincrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "nummultby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "numpowby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "objkeys": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "objlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "resp": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "set": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "strappend": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "strlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "toggle": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "type": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "std": {
    "vadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vcard": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vdim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vemb": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vgetattr": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vinfo": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vismember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vlinks": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vrandmember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vrem": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vsetattr": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "vsim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "acl": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "cat": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "deluser": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "dryrun": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "genpass": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "getuser": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "list": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "load": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "log": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "save": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "setuser": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "users": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "whoami": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "append": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arcount": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "ardel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "ardelrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "argetrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "argrep": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arinfo": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arinsert": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arlastitems": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "armget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "armset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arnext": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arring": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arscan": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arseek": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "arset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "asking": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "auth": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "bgrewriteaof": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "bgsave": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "bitcount": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bitfield": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bitfield_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bitop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bitpos": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "blmove": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "blmpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "blpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "brpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "brpoplpush": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bzmpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bzpopmax": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "bzpopmin": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "client": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "caching": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "getname": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "getredir": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "id": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "info": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "kill": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "list": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "no-evict": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "no-touch": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "pause": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "reply": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "setinfo": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "setname": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "tracking": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "trackinginfo": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "unblock": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "unpause": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "cluster": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "addslots": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "addslotsrange": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "bumpepoch": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "count-failure-reports": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "countkeysinslot": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "delslots": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "delslotsrange": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "failover": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "flushslots": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "forget": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "getkeysinslot": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "info": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "keyslot": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "links": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "meet": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "migration": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "myid": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "myshardid": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "nodes": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "replicas": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "replicate": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "reset": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "saveconfig": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "set-config-epoch": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "setslot": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "shards": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "slaves": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "slot-stats": {
          "request": "all_shards",
          "response": "default-keyless",
          "isKeyless": true
        },
        "slots": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "syncslots": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "command": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "count": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "docs": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "getkeys": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "getkeysandflags": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "info": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "list": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "config": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "get": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "resetstat": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "rewrite": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "set": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        }
      }
    },
    "copy": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "dbsize": {
      "request": "all_shards",
      "response": "agg_sum",
      "isKeyless": true
    },
    "debug": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "decr": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "decrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "del": {
      "request": "multi_shard",
      "response": "agg_sum",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "range",
            "lastKey": -1,
            "keyStep": 1,
            "limit": 0
          }
        }
      ]
    },
    "delex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "digest": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "discard": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "dump": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "echo": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "eval": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "eval_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "evalsha": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "evalsha_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "exec": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "exists": {
      "request": "multi_shard",
      "response": "agg_sum",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "range",
            "lastKey": -1,
            "keyStep": 1,
            "limit": 0
          }
        }
      ]
    },
    "expire": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "expireat": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "expiretime": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "failover": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "fcall": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "fcall_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "flushall": {
      "request": "all_shards",
      "response": "all_succeeded",
      "isKeyless": true
    },
    "flushdb": {
      "request": "all_shards",
      "response": "all_succeeded",
      "isKeyless": true
    },
    "function": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "delete": {
          "request": "all_shards",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "dump": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "flush": {
          "request": "all_shards",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "kill": {
          "request": "all_shards",
          "response": "one_succeeded",
          "isKeyless": true
        },
        "list": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "load": {
          "request": "all_shards",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "restore": {
          "request": "all_shards",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "stats": {
          "request": "all_shards",
          "response": "special",
          "isKeyless": true
        }
      }
    },
    "geoadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "geodist": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "geohash": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "geopos": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "georadius": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "georadius_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "georadiusbymember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "georadiusbymember_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "geosearch": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "geosearchstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "get": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "getbit": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "getdel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "getex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "getrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "getset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hdel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hello": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "hexists": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hexpire": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hexpireat": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hexpiretime": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hgetall": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hgetdel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hgetex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hincrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hincrbyfloat": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hkeys": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hmget": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hmset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hotkeys": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "get": {
          "request": "special",
          "response": "special",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "reset": {
          "request": "special",
          "response": "default-keyless",
          "isKeyless": true
        },
        "start": {
          "request": "special",
          "response": "default-keyless",
          "isKeyless": true
        },
        "stop": {
          "request": "special",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "hpersist": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hpexpire": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hpexpireat": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hpexpiretime": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hpttl": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hrandfield": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hscan": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hsetex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hsetnx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hstrlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "httl": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "hvals": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "incr": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "incrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "incrbyfloat": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "increx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "all_shards",
      "response": "special",
      "isKeyless": true
    },
    "keys": {
      "request": "all_shards",
      "response": "default-keyless",
      "isKeyless": true
    },
    "lastsave": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "latency": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "doctor": {
          "request": "all_nodes",
          "response": "special",
          "isKeyless": true
        },
        "graph": {
          "request": "all_nodes",
          "response": "special",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "histogram": {
          "request": "all_nodes",
          "response": "special",
          "isKeyless": true
        },
        "history": {
          "request": "all_nodes",
          "response": "special",
          "isKeyless": true
        },
        "latest": {
          "request": "all_nodes",
          "response": "special",
          "isKeyless": true
        },
        "reset": {
          "request": "all_nodes",
          "response": "agg_sum",
          "isKeyless": true
        }
      }
    },
    "lcs": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lindex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "linsert": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "llen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lmove": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lmpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lolwut": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "lpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lpos": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lpush": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lpushx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lrem": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "lset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "ltrim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "memory": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "doctor": {
          "request": "all_shards",
          "response": "special",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "malloc-stats": {
          "request": "all_shards",
          "response": "special",
          "isKeyless": true
        },
        "purge": {
          "request": "all_shards",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "stats": {
          "request": "all_shards",
          "response": "special",
          "isKeyless": true
        },
        "usage": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        }
      }
    },
    "mget": {
      "request": "multi_shard",
      "response": "default-keyed",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "range",
            "lastKey": -1,
            "keyStep": 1,
            "limit": 0
          }
        }
      ]
    },
    "migrate": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "module": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "list": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "load": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "loadex": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "unload": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "monitor": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "move": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "mset": {
      "request": "multi_shard",
      "response": "all_succeeded",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "range",
            "lastKey": -1,
            "keyStep": 2,
            "limit": 0
          }
        }
      ]
    },
    "msetex": {
      "request": "multi_shard",
      "response": "all_succeeded",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "keynum",
            "keyNumIdx": 0,
            "firstKey": 1,
            "keyStep": 2
          }
        }
      ]
    },
    "msetnx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "multi": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "object": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "encoding": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "freq": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "idletime": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "refcount": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        }
      }
    },
    "persist": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pexpire": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pexpireat": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pexpiretime": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pfadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pfcount": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pfdebug": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pfmerge": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "pfselftest": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "ping": {
      "request": "all_shards",
      "response": "all_succeeded",
      "isKeyless": true
    },
    "psetex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "psubscribe": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "psync": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "pttl": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "publish": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "pubsub": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "channels": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "numpat": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "numsub": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "shardchannels": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "shardnumsub": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        }
      }
    },
    "punsubscribe": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "quit": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "randomkey": {
      "request": "all_shards",
      "response": "special",
      "isKeyless": true
    },
    "readonly": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "readwrite": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "rename": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "renamenx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "replconf": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "replicaof": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "reset": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "restore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "restore-asking": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "role": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "rpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "rpoplpush": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "rpush": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "rpushx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "save": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "scan": {
      "request": "special",
      "response": "special",
      "isKeyless": true
    },
    "scard": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "script": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "debug": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "exists": {
          "request": "all_shards",
          "response": "agg_logical_and",
          "isKeyless": true
        },
        "flush": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "kill": {
          "request": "all_shards",
          "response": "one_succeeded",
          "isKeyless": true
        },
        "load": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        }
      }
    },
    "sdiff": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sdiffstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "select": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "set": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "setbit": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "setex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "setnx": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "setrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "shutdown": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "sinter": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sintercard": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sinterstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sismember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "slaveof": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "slowlog": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "get": {
          "request": "all_nodes",
          "response": "default-keyless",
          "isKeyless": true
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "len": {
          "request": "all_nodes",
          "response": "agg_sum",
          "isKeyless": true
        },
        "reset": {
          "request": "all_nodes",
          "response": "all_succeeded",
          "isKeyless": true
        }
      }
    },
    "smembers": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "smismember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "smove": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sort": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sort_ro": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "spop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "spublish": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "srandmember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "srem": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sscan": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "ssubscribe": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "strlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "subscribe": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "substr": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sunion": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sunionstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "sunsubscribe": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "swapdb": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "sync": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "time": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "touch": {
      "request": "multi_shard",
      "response": "agg_sum",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "range",
            "lastKey": -1,
            "keyStep": 1,
            "limit": 0
          }
        }
      ]
    },
    "trimslots": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "ttl": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "type": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "unlink": {
      "request": "multi_shard",
      "response": "agg_sum",
      "isKeyless": false,
      "keySpecs": [
        {
          "beginSearch": {
            "type": "index",
            "index": 1
          },
          "findKeys": {
            "type": "range",
            "lastKey": -1,
            "keyStep": 1,
            "limit": 0
          }
        }
      ]
    },
    "unsubscribe": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "unwatch": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "wait": {
      "request": "all_shards",
      "response": "agg_min",
      "isKeyless": true
    },
    "waitaof": {
      "request": "all_shards",
      "response": "agg_min",
      "isKeyless": true
    },
    "watch": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xack": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xackdel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xautoclaim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xcfgset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xclaim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xdel": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xdelex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xgroup": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "create": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "createconsumer": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "delconsumer": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "destroy": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "setid": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        }
      }
    },
    "xidmprecord": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xinfo": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true,
      "subcommands": {
        "consumers": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "groups": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        },
        "help": {
          "request": "default-keyless",
          "response": "default-keyless",
          "isKeyless": true
        },
        "stream": {
          "request": "default-keyed",
          "response": "default-keyed",
          "isKeyless": false
        }
      }
    },
    "xlen": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xnack": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xpending": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xread": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xreadgroup": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xrevrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xsetid": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "xtrim": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zadd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zcard": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zcount": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zdiff": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zdiffstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zincrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zinter": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zintercard": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zinterstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zlexcount": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zmpop": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zmscore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zpopmax": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zpopmin": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrandmember": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrangebylex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrangebyscore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrangestore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrem": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zremrangebylex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zremrangebyrank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zremrangebyscore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrevrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrevrangebylex": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrevrangebyscore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zrevrank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zscan": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zscore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zunion": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "zunionstore": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "tdigest": {
    "add": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "byrank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "byrevrank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "cdf": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "create": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "max": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "merge": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "min": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "quantile": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "rank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "reset": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "revrank": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "trimmed_mean": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "timeseries": {
    "refreshcluster": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    }
  },
  "topk": {
    "add": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "count": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "incrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "list": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "query": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "reserve": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  },
  "ts": {
    "add": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "alter": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "create": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "createrule": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "decrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "del": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "deleterule": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "get": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "incrby": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "info": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "madd": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "mget": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "mrange": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "mrevrange": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "queryindex": {
      "request": "default-keyless",
      "response": "default-keyless",
      "isKeyless": true
    },
    "range": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    },
    "revrange": {
      "request": "default-keyed",
      "response": "default-keyed",
      "isKeyless": false
    }
  }
} as const;
