/**
 * Regenerates `lib/command-metadata/command-metadata-data.ts`
 * from a live Redis server's COMMAND reply.
 *
 * The metadata derivation is shared with `DynamicPolicyResolverFactory`, so the
 * generated static data is exactly what the dynamic resolver would build at
 * runtime against the same server, minus the HLD curation defined in
 * `command-metadata-overrides.ts` (internal/deprecated/cluster-admin commands).
 *
 * Usage:
 *   npm run generate:metadata --workspace=packages/client -- redis://localhost:6379
 *
 * The Redis URL is taken from the first CLI argument, then the REDIS_URL
 * environment variable, and defaults to redis://localhost:6379.
 *
 * Run against a server with all bundled modules loaded (e.g. Redis 8.8) so
 * module commands (ft, json, bf, ...) are included.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createClient } from '../index';
import { transformCommandReply, type CommandRawReply } from '../lib/commands/generic-transformers';
import { DynamicPolicyResolverFactory } from '../lib/command-metadata/dynamic-policy-resolver-factory';
import type { CommandMetadataRecords, ModuleMetadataRecords } from '../lib/command-metadata/types';
import type { CommandMetadata } from '../lib/command-metadata/policies-constants';
import { EXCLUDED_MODULES, EXCLUDED_COMMANDS, COMMAND_OVERRIDES } from './command-metadata-overrides';

const OUTPUT_PATH = resolve(__dirname, '../lib/command-metadata/command-metadata-data.ts');

function sortedByKey<T>(record: Record<string, T>, mapValue: (value: T) => T): Record<string, T> {
  const sorted: Record<string, T> = {};
  // Lowercased to match StaticMetadataResolver's lookup normalization.
  for (const key of Object.keys(record).sort()) {
    sorted[key.toLowerCase()] = mapValue(record[key]);
  }
  return sorted;
}

function sortCommandMetadata(policies: CommandMetadata): CommandMetadata {
  return {
    ...policies,
    subcommands: policies.subcommands
      ? sortedByKey(policies.subcommands, sortCommandMetadata)
      : undefined
  };
}

// Sort modules, commands and subcommands alphabetically so regeneration
// produces stable diffs regardless of the order the server lists commands in.
function sortModuleMetadataRecords(records: ModuleMetadataRecords): ModuleMetadataRecords {
  return sortedByKey(records, (commands: CommandMetadataRecords) =>
    sortedByKey(commands, sortCommandMetadata)
  );
}

// Applies the HLD curation from command-metadata-overrides.ts. Expects
// lowercased records (i.e. run after sortModuleMetadataRecords).
function curate(records: ModuleMetadataRecords): ModuleMetadataRecords {
  const curated: ModuleMetadataRecords = {};

  for (const [moduleName, commands] of Object.entries(records)) {
    if (EXCLUDED_MODULES.has(moduleName)) continue;

    curated[moduleName] = {};
    for (const [commandName, policies] of Object.entries(commands)) {
      const fullName = `${moduleName}.${commandName}`;
      if (EXCLUDED_COMMANDS.has(fullName)) continue;

      // Shallow-merge: override keys win, unspecified keys keep the server value.
      const override = COMMAND_OVERRIDES[fullName];
      curated[moduleName][commandName] = override ? { ...policies, ...override } : policies;
    }
  }

  return curated;
}

async function main() {
  const url = process.argv[2] ?? process.env.REDIS_URL ?? 'redis://localhost:6379';
  const client = createClient({ url });
  await client.connect();

  try {
    const rawCommands = await client.sendCommand<Array<CommandRawReply>>(['COMMAND']);
    const commands = rawCommands.map(transformCommandReply);
    const policies = curate(sortModuleMetadataRecords(
      DynamicPolicyResolverFactory.buildModuleMetadataRecords(commands)
    ));

    const info = await client.sendCommand<string>(['INFO', 'server']);
    const version = /redis_version:(\S+)/.exec(info)?.[1] ?? 'unknown';

    const content = [
      '// This file is auto-generated by scripts/generate-command-metadata-data.ts — do not edit manually.',
      `// Source: Redis ${version}, ${Object.values(policies).reduce((sum, commands) => sum + Object.keys(commands).length, 0)} commands.`,
      'import { ModuleMetadataRecords } from "./types";',
      '',
      `export const COMMAND_METADATA: ModuleMetadataRecords = ${JSON.stringify(policies, null, 2)} as const;`,
      ''
    ].join('\n');

    writeFileSync(OUTPUT_PATH, content);
    console.log(`Wrote ${OUTPUT_PATH} (Redis ${version})`);
  } finally {
    client.destroy();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
