/**
 * Regenerates `lib/cluster/request-response-policies/static-policies-data.ts`
 * from a live Redis server's COMMAND reply.
 *
 * The policy derivation is shared with `DynamicPolicyResolverFactory`, so the
 * generated static data is exactly what the dynamic resolver would build at
 * runtime against the same server, minus the HLD curation defined in
 * `static-policies-overrides.ts` (internal/deprecated/cluster-admin commands).
 *
 * Usage:
 *   npm run generate:policies --workspace=packages/client -- redis://localhost:6379
 *
 * The Redis URL is taken from the first CLI argument, then the REDIS_URL
 * environment variable, and defaults to redis://localhost:6379.
 *
 * Run against a server with all bundled modules loaded (e.g. Redis 8.8) so
 * module commands (ft, json, bf, ...) are included.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createClient } from '../index';
import { transformCommandReply, type CommandRawReply } from '../lib/commands/generic-transformers';
import { DynamicPolicyResolverFactory } from '../lib/cluster/request-response-policies/dynamic-policy-resolver-factory';
import type { CommandPolicyRecords, ModulePolicyRecords } from '../lib/cluster/request-response-policies/types';
import type { CommandPolicies } from '../lib/cluster/request-response-policies/policies-constants';
import { EXCLUDED_MODULES, EXCLUDED_COMMANDS, COMMAND_OVERRIDES } from './static-policies-overrides';

const OUTPUT_PATH = resolve(__dirname, '../lib/cluster/request-response-policies/static-policies-data.ts');

function sortedByKey<T>(record: Record<string, T>, mapValue: (value: T) => T): Record<string, T> {
  const sorted: Record<string, T> = {};
  // Lowercased to match StaticPolicyResolver's lookup normalization.
  for (const key of Object.keys(record).sort()) {
    sorted[key.toLowerCase()] = mapValue(record[key]);
  }
  return sorted;
}

function sortCommandPolicies(policies: CommandPolicies): CommandPolicies {
  return {
    ...policies,
    subcommands: policies.subcommands
      ? sortedByKey(policies.subcommands, sortCommandPolicies)
      : undefined
  };
}

// Sort modules, commands and subcommands alphabetically so regeneration
// produces stable diffs regardless of the order the server lists commands in.
function sortModulePolicyRecords(records: ModulePolicyRecords): ModulePolicyRecords {
  return sortedByKey(records, (commands: CommandPolicyRecords) =>
    sortedByKey(commands, sortCommandPolicies)
  );
}

// Applies the HLD curation from static-policies-overrides.ts. Expects
// lowercased records (i.e. run after sortModulePolicyRecords).
function curate(records: ModulePolicyRecords): ModulePolicyRecords {
  const curated: ModulePolicyRecords = {};

  for (const [moduleName, commands] of Object.entries(records)) {
    if (EXCLUDED_MODULES.has(moduleName)) continue;

    curated[moduleName] = {};
    for (const [commandName, policies] of Object.entries(commands)) {
      const fullName = `${moduleName}.${commandName}`;
      if (EXCLUDED_COMMANDS.has(fullName)) continue;

      curated[moduleName][commandName] = COMMAND_OVERRIDES[fullName] ?? policies;
    }
  }

  return curated;
}

async function main() {
  const url = process.argv[2] ?? process.env.REDIS_URL ?? 'redis://localhost:6379';
  const client = createClient({ url });
  await client.connect();

  try {
    const rawCommands = await client.sendCommand<Array<CommandRawReply>>(['COMMAND']);
    const commands = rawCommands.map(transformCommandReply);
    const policies = curate(sortModulePolicyRecords(
      DynamicPolicyResolverFactory.buildModulePolicyRecords(commands)
    ));

    const info = await client.sendCommand<string>(['INFO', 'server']);
    const version = /redis_version:(\S+)/.exec(info)?.[1] ?? 'unknown';

    const content = [
      '// This file is auto-generated by scripts/generate-static-policies-data.ts — do not edit manually.',
      `// Source: Redis ${version}, ${Object.values(policies).reduce((sum, commands) => sum + Object.keys(commands).length, 0)} commands.`,
      'import { ModulePolicyRecords } from "./types";',
      '',
      `export const POLICIES: ModulePolicyRecords = ${JSON.stringify(policies, null, 2)} as const;`,
      ''
    ].join('\n');

    writeFileSync(OUTPUT_PATH, content);
    console.log(`Wrote ${OUTPUT_PATH} (Redis ${version})`);
  } finally {
    client.destroy();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
