name: Documentation

on:
  push:
    branches:
      - master
      - v4.0

permissions:
  contents: read

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to push generated docs to gh-pages
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v6
      - name: Install Packages
        run: npm ci
      - name: Build Packages
        run: npm run build
      - name: Generate Documentation
        run: npm run documentation
      - name: Upload
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
